const mongoose = require('mongoose');
const { prettyLogger: logger, error } = require('../../services/logger');
const { dbConfig } = require('../../config/appConfig');

let isConnected = false;

/**
 * Get the MongoDB connection URI.
 * This function constructs the URI from the database configuration.
 * If the URI is already set, it returns that.
 * If any required configuration is missing, it throws an error.
 * @returns {string} MongoDB connection URI
 * @throws {Error} If the database configuration is incomplete
 */
const getDbURI = () => {
  const { uri: dbURI } = dbConfig;
  // If dbURI is provided, use it directly
  if (!dbURI || typeof dbURI !== 'string') {
    throw new Error('Missing or invalid DB_URI in environment');
  }
  if (!dbURI.startsWith('mongodb://') && !dbURI.startsWith('mongodb+srv://')) {
    throw new Error(
      'Invalid dbURI format, must start with "mongodb://" or "mongodb+srv://"'
    );
  }
  return dbURI;
};

/**
 * Connect to MongoDB using Mongoose.
 * This function establishes a connection to the MongoDB database.
 * It uses the connection URI generated by getDbURI.
 * If the connection is already established, it does nothing.
 * It also sets up a listener for the SIGINT signal to close the connection gracefully.
 * @returns {Promise<void>} Resolves when the connection is established
 * @throws {Error} If the connection fails
 */
async function connectToMongo() {
  const uri = getDbURI();
  if (!uri) throw new Error('Missing MONGODB_URI in environment');

  if (isConnected) return;

  try {
    await mongoose.connect(uri);

    isConnected = true;
    logger.showMsg('✅ Connected to MongoDB via Mongoose');
  } catch (err) {
    logger.showErrorMsg('❌ MongoDB connection error');
    error('MongoDB connection failed', {
      error: err.message,
      stack: err.stack,
    });
    /* eslint-disable no-process-exit */
    process.exit(1);
  }
}

function getMongoose() {
  if (!isConnected) {
    throw new Error('Mongoose not connected. Call connectToMongo() first.');
  }
  return mongoose;
}

module.exports = {
  connectToMongo,
  getMongoose,
  closeConnection: async () => {
    if (isConnected) {
      await mongoose.connection.close();
      isConnected = false;
      logger.showMsg('🔌 MongoDB connection closed');
    } else {
      logger.showMsg('🔌 No active MongoDB connection to close');
    }
  },
};
